# Generated by Django 5.2 on 2025-04-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_whyus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vision',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/'),
        ),
    ]
