# Generated by Django 5.2 on 2025-04-05 06:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +255 followed by 9 digits.', regex='^\\+255[0-9]{9}$')])),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
